[package]
name = "rustreader"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rustreader"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
extractous = "0.2.0"
